
apiVersion: v1
kind: Service
metadata:
  name: vizceral-chart
  labels:
    app: chart
    chart: chart-0.1.0
    release: vizceral
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: vizceral
  selector:
    app: chart
    release: vizceral
---
# Source: chart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizceral-chart
  labels:
    app: chart
    chart: chart-0.1.0
    release: vizceral
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chart
        release: vizceral
    spec:
      containers:
        - name: chart
          image: "jpogue/vizceral:master"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {}



