steps:
- name: gcr.io/cloud-builders/go
  env: ['PROJECT_ROOT=vrctlviz']
  entrypoint: 'ash'
  args:
   - -c
   - |
     . /builder/prepare_workspace.inc 
     prepare_workspace || exit
     env | sort
     ls
     go build
     mkdir -p rootfs/usr/bin
     cp vrctlviz rootfs/usr/bin/vrctlviz
     ls rootfs/usr/bin
     mkdir -p converter/rootfs/usr/bin
     cp vrctlviz converter/rootfs/usr/bin/vrctlviz
     ls converter/rootfs/usr/bin
     cp vrctlviz vrctlviz-alpine
     export GOOS=linux
     export GOARCH=amd64
     go build
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'vrctlviz', 'gs://itc3-public/']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'vrctlviz-alpine', 'gs://itc3-public/']
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/vizceral:$BRANCH_NAME", "-f", "vizceral/Dockerfile", "vizceral"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME", "-f", "Dockerfile", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/converter:$BRANCH_NAME", "-f", "converter/Dockerfile", "converter"]
images:
  - "gcr.io/itc3-production/vrctlviz/vizceral:$BRANCH_NAME"
  - "gcr.io/itc3-production/vrctlviz/converter:$BRANCH_NAME"
  - "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME"

