steps:
- name: gcr.io/cloud-builders/go
  env: ['PROJECT_ROOT=vrctlviz']
  entrypoint: 'ash'
  args:
   - -c
   - |
     . /builder/prepare_workspace.inc 
     prepare_workspace || exit
     env | sort
     cd collector
     ls
     go get
     go build
     mkdir -p rootfs/usr/bin
     ls
     cp collector rootfs/usr/bin/vrctlviz
     ls rootfs/usr/bin
     mkdir -p ../server/rootfs/usr/bin
     cp collector ../server/rootfs/vrctlviz
     ls ../server/rootfs
     cp collector vrctlviz-alpine
     export GOOS=linux
     export GOARCH=amd64
     go get
     go build
     mv collector vrctlviz
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'collector/vrctlviz', 'gs://itc3-public/']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'collector/vrctlviz-alpine', 'gs://itc3-public/']
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/vizceral:$BRANCH_NAME", "-f", "vizceral/Dockerfile", "vizceral"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME", "-f", "collector/Dockerfile", "collector"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/server:$BRANCH_NAME", "-f", "server/Dockerfile", "server"]
images:
  - "gcr.io/itc3-production/vrctlviz/vizceral:$BRANCH_NAME"
  - "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME"
  - "gcr.io/itc3-production/vrctlviz/server:$BRANCH_NAME"
