steps:
- name: gcr.io/cloud-builders/go
  entrypoint: 'ash'
  args:
   - -c
   - |
     . /builder/prepare_workspace.inc 
     prepare_workspace || exit
     env | sort
     ls
     export GOOS=linux
     export GOARCH=amd64
     go get
     go build
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME", "-f", "vizceral/Dockerfile", "vizceral"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'vrctlviz', 'gs://itc3-public/']
images:
  - "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME"


