steps:
- name: gcr.io/cloud-builders/go
  entrypoint: 'ash'
  args:
   - -c
   - |
     . /builder/prepare_workspace.inc 
     prepare_workspace || exit
     env | sort
     ls
     mkdir -p /go/src/github.com/itc3-devops/vrctlviz
     cp -a * /go/src/github.com/itc3-devops/vrctlviz
     cd /go/src/github.com/itc3-devops/vrctlviz
     export GOPATH=/go
     export GOBIN=/go/bin
     export GOOS=linux
     export GOARCH=amd64
     go get
     go build
     mv vrctlviz vrctlviz-amd64
     export GOOS=linux
     export GOARCH=i386
     go get
     go build
     mv vrctlviz vrctlviz-386
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME", "-f", "Dockerfile", "."]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'vrctlviz', 'gs://itc3-public/']
images:
  - "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME"


