steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['generate']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-a', '-ldflags', "'-s'", '-installsuffix', 'cgo', 'collector/main.go']
  env: [
    'CGO_ENABLED=0',
    'GOOS=linux'
  ]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME", "-f", "Dockerfile", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME", "-f", "Dockerfile", "."]
images:
  - "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME"
  - "gcr.io/itc3-production/vrctlviz/collector:$BRANCH_NAME"

