steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME", "-f", "Dockerfile", "."]
images:
  - "gcr.io/itc3-production/vrctlviz:$BRANCH_NAME"

