#!/bin/sh
source ~/.vrctlviz.yaml
chmod +x /usr/bin/vrctlviz


for x in $(find /etc/service -iname run); do
chmod +x "$x"
sed -i 's/\r//g' "$x"
done
export LD_PRELOAD=/lib/runit-docker.so
exec runsvdir /etc/service
