#!/bin/bash

if [ -z "$LanInterface" ]; then
export LanInterface
LanInterface=$(ip route list | awk '/^default/ {print $5}')
fi

if [ -z "$Interface" ]; then
export Interface
Interface=$(ip route list | awk '/^default/ {print $5}')
fi
exec /usr/bin/vrctlviz run